# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: None

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/qqc2-desktop-style': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kirigami-addons': '@latest-kf6'
Options:
  require-passing-tests-on: ['Linux']

